name: Kafka Connector CKO Deploy

on:
  push:
    branches: [ cko-master ]
  pull_request:
    branches: '**'

jobs:
  build_and_test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: "Install Java 8"
      uses: actions/setup-java@v3
      with:
        java-version: 8
        distribution: 'temurin'
        cache: 'maven'
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        architecture: 'x64'

    - name: Build Confluent-compatible package
      run: mvn -f pom_confluent.xml -DskipTests clean package
    
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest-cko"
        prerelease: true
        title: "CKO Kafka Connect Release"
        files: |
          target/components/packages/**.zip
